# podman build -t localhost/toolbox-local:37 .
# toolbox create -i localhost/toolbox-local:37 fedora-toolbox-37

FROM registry.fedoraproject.org/fedora-toolbox:37

# Update base packages
#RUN dnf -y upgrade

# Install packages
RUN dnf install -y @development-tools jq python-pip golang mlocate tmux vim-enhanced pcp-system-tools

# Install kcli
RUN dnf -y copr enable karmab/kcli \
    && dnf -y install kcli

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf
