# podman build -t localhost/ocaml:5 .

FROM registry.fedoraproject.org/fedora-toolbox:39

# Disable h264 repo
RUN dnf config-manager --set-disabled fedora-cisco-openh264

# Update base packages
#RUN dnf -y upgrade

# Install opam
# - fira-code-fonts to be revaluated
# - glibc-static for static linking
# - gmp-devel for ocaml emacs integration
RUN dnf install -y \
   emacs-nox \
   fira-code-fonts \
   glibc-static \
   gmp-devel \
   opam

# Inicialize opam
RUN opam init --disable-sandboxing --root /opt/opam
RUN opam install -y --root /opt/opam \
   core \
   dune \
   dune-release \
   merlin \
   ocaml-lsp-server \
   ocamlformat \
   ocp-indent \
   odoc \
   ounit2 \
   tuareg \
   user-setup \
   utop

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf
RUN echo "toolbox create -i localhost/ocaml:5 ocaml"
