# podman build -t localhost/ocaml:5 .
# toolbox create -i localhost/ocaml:5 ocaml

FROM registry.fedoraproject.org/fedora-toolbox:38

# Update base packages
RUN dnf -y upgrade

# Install opam
RUN dnf install -y opam

# Inicialize opam
RUN opam init --disable-sandboxing

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf
