##podman build --build-arg user=$USER -t localhost/toolbox:39 .
# podman build -t localhost/toolbox:39 .

FROM registry.fedoraproject.org/fedora-toolbox:39

#ARG user

# Disable h264 repo
RUN dnf config-manager --set-disabled fedora-cisco-openh264

# Update base packages
#RUN dnf -y upgrade

# Install packages
# - glibc-static and libzstd-static for ocaml static linking
# - jq, openssl for kind.sh
# Removed: - emacs-nox and gmp-devel for ocaml emacs integration
# - ncurses-devel for python readline
# - openssl-devel for compiling python
RUN dnf install -y \
   @development-tools \
   awscli2 \
   bats \
   flatpak-builder \
   glibc-static \
   jq \
   libzstd-static \
   ncurses-devel \
   openssl \
   openssl-devel \
   p7zip \
   xev
#python-pip
#qemu libvirt libvirt-daemon-driver-qemu qemu-kvm

# Install kcli
RUN dnf -y copr enable karmab/kcli \
    && dnf -y install kcli

# Configure virt groups
#RUN sudo usermod -aG qemu,libvirt $user

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf

RUN echo "toolbox create -i localhost/toolbox:39 fedora-toolbox-39"
