# podman build --build-arg user=$USER -t localhost/mirage .

FROM registry.fedoraproject.org/fedora-toolbox:38

ARG user

# Disable h264 repo
RUN dnf config-manager --set-disabled fedora-cisco-openh264

# Update base packages
RUN dnf -y upgrade

# Install opam
# - glibc-static for static linking
# - gmp-devel for ocaml emacs integration
# - libseccomp-devel for mirage
RUN dnf install -y \
   emacs-nox \
   glibc-static \
   gmp-devel \
   libseccomp-devel \
   opam

# Inicialize opam
RUN useradd $user
USER $user
RUN opam init --disable-sandboxing --compiler 4.14.1
RUN opam install -y \
   core \
   dune \
   dune-release \
   merlin \
   mirage \
   ocaml-lsp-server \
   ocamlformat \
   ocp-indent \
   odoc \
   ounit2 \
   tuareg \
   user-setup \
   utop

# Clean
USER root
RUN mv /home/$user/.opam /usr/share/opam
RUN userdel -r $user
RUN dnf clean all \
    && rm -rf /var/cache/dnf
RUN echo "toolbox create -i localhost/mirage mirage"
