# podman build -t localhost/mirage .

FROM registry.fedoraproject.org/fedora-toolbox:39

# Disable h264 repo
RUN dnf config-manager --set-disabled fedora-cisco-openh264

# Update base packages
#RUN dnf -y upgrade

# Install opam
# - glibc-static for static linking
# - gmp-devel for ocaml emacs integration
# - libseccomp-devel for mirage
RUN dnf install -y \
   emacs-nox \
   glibc-static \
   gmp-devel \
   libseccomp-devel \
   opam

# Inicialize opam
RUN opam init --disable-sandboxing --root /opt/opam --compiler 4.14.1
RUN opam install -y --root /opt/opam \
   core \
   dune \
   dune-release \
   merlin \
   mirage \
   ocaml-lsp-server \
   ocamlformat \
   ocp-indent \
   odoc \
   ounit2 \
   tuareg \
   user-setup \
   utop

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf
RUN echo "toolbox create -i localhost/mirage mirage"
RUN echo "toolbox enter mirage"

