##podman build --build-arg user=$USER -t localhost/toolbox:38 .
# podman build -t localhost/toolbox:38 .

FROM registry.fedoraproject.org/fedora-toolbox:38

#ARG user

# Disable h264 repo
RUN dnf config-manager --set-disabled fedora-cisco-openh264 

# Update base packages
RUN dnf -y upgrade

# Install packages
# - jq for kind.sh
RUN dnf install -y @development-tools ansible awscli2 golang ipython jq python-pip xev
#qemu libvirt libvirt-daemon-driver-qemu qemu-kvm 

# Install kcli
RUN dnf -y copr enable karmab/kcli \
    && dnf -y install kcli

# Configure virt groups
#RUN sudo usermod -aG qemu,libvirt $user

# Clean
RUN dnf clean all \
    && rm -rf /var/cache/dnf

RUN echo "toolbox create -i localhost/toolbox:38 fedora-toolbox-38"
